//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.08 at 10:57:22 AM EEST 
//


package org.fortune.schema._2_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stylesheet" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="description">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title-info">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="genre" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0/genres>genreType">
 *                                     &lt;attribute name="match" type="{http://www.w3.org/2001/XMLSchema}integer" default="100" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="author" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType">
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="book-title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType"/>
 *                             &lt;element name="annotation" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
 *                             &lt;element name="keywords" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType" minOccurs="0"/>
 *                             &lt;element name="coverpage" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" maxOccurs="unbounded"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}language"/>
 *                             &lt;element name="src-lang" type="{http://www.w3.org/2001/XMLSchema}language" minOccurs="0"/>
 *                             &lt;element name="translator" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="document-info">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/>
 *                             &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/>
 *                             &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="publish-info" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *                             &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
 *                             &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="custom-info" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0>textFieldType">
 *                           &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="body" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" minOccurs="0"/>
 *                   &lt;element name="title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}titleType" minOccurs="0"/>
 *                   &lt;element name="epigraph" type="{http://www.gribuser.ru/xml/fictionbook/2.0}epigraphType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="section" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sectionType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="binary" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
 *                 &lt;attribute name="content-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stylesheet",
    "description",
    "body",
    "binary"
})
@XmlRootElement(name = "FictionBook")
public class FictionBook {

    protected List<FictionBook.Stylesheet> stylesheet;
    @XmlElement(required = true)
    protected FictionBook.Description description;
    @XmlElement(required = true)
    protected List<FictionBook.Body> body;
    protected List<FictionBook.Binary> binary;

    /**
     * Gets the value of the stylesheet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stylesheet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStylesheet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FictionBook.Stylesheet }
     * 
     * 
     */
    public List<FictionBook.Stylesheet> getStylesheet() {
        if (stylesheet == null) {
            stylesheet = new ArrayList<FictionBook.Stylesheet>();
        }
        return this.stylesheet;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link FictionBook.Description }
     *     
     */
    public FictionBook.Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link FictionBook.Description }
     *     
     */
    public void setDescription(FictionBook.Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the body property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the body property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBody().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FictionBook.Body }
     * 
     * 
     */
    public List<FictionBook.Body> getBody() {
        if (body == null) {
            body = new ArrayList<FictionBook.Body>();
        }
        return this.body;
    }

    /**
     * Gets the value of the binary property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the binary property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBinary().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FictionBook.Binary }
     * 
     * 
     */
    public List<FictionBook.Binary> getBinary() {
        if (binary == null) {
            binary = new ArrayList<FictionBook.Binary>();
        }
        return this.binary;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>base64Binary">
     *       &lt;attribute name="content-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Binary {

        @XmlValue
        protected byte[] value;
        @XmlAttribute(name = "content-type", required = true)
        protected String contentType;
        @XmlAttribute(name = "id", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     byte[]
         */
        public byte[] getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     byte[]
         */
        public void setValue(byte[] value) {
            this.value = value;
        }

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" minOccurs="0"/>
     *         &lt;element name="title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}titleType" minOccurs="0"/>
     *         &lt;element name="epigraph" type="{http://www.gribuser.ru/xml/fictionbook/2.0}epigraphType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="section" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sectionType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "image",
        "title",
        "epigraph",
        "section"
    })
    public static class Body {

        protected ImageType image;
        protected TitleType title;
        protected List<EpigraphType> epigraph;
        @XmlElement(required = true)
        protected List<SectionType> section;
        @XmlAttribute(name = "name")
        protected String name;
        @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "language")
        protected String lang;

        /**
         * Gets the value of the image property.
         * 
         * @return
         *     possible object is
         *     {@link ImageType }
         *     
         */
        public ImageType getImage() {
            return image;
        }

        /**
         * Sets the value of the image property.
         * 
         * @param value
         *     allowed object is
         *     {@link ImageType }
         *     
         */
        public void setImage(ImageType value) {
            this.image = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link TitleType }
         *     
         */
        public TitleType getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link TitleType }
         *     
         */
        public void setTitle(TitleType value) {
            this.title = value;
        }

        /**
         * Gets the value of the epigraph property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the epigraph property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpigraph().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EpigraphType }
         * 
         * 
         */
        public List<EpigraphType> getEpigraph() {
            if (epigraph == null) {
                epigraph = new ArrayList<EpigraphType>();
            }
            return this.epigraph;
        }

        /**
         * Gets the value of the section property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SectionType }
         * 
         * 
         */
        public List<SectionType> getSection() {
            if (section == null) {
                section = new ArrayList<SectionType>();
            }
            return this.section;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the lang property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLang() {
            return lang;
        }

        /**
         * Sets the value of the lang property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLang(String value) {
            this.lang = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title-info">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="genre" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0/genres>genreType">
     *                           &lt;attribute name="match" type="{http://www.w3.org/2001/XMLSchema}integer" default="100" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="author" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType">
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="book-title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType"/>
     *                   &lt;element name="annotation" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
     *                   &lt;element name="keywords" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType" minOccurs="0"/>
     *                   &lt;element name="coverpage" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" maxOccurs="unbounded"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}language"/>
     *                   &lt;element name="src-lang" type="{http://www.w3.org/2001/XMLSchema}language" minOccurs="0"/>
     *                   &lt;element name="translator" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="document-info">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/>
     *                   &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/>
     *                   &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/>
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="publish-info" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
     *                   &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
     *                   &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="custom-info" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0>textFieldType">
     *                 &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "titleInfo",
        "documentInfo",
        "publishInfo",
        "customInfo"
    })
    public static class Description {

        @XmlElement(name = "title-info", required = true)
        protected FictionBook.Description.TitleInfo titleInfo;
        @XmlElement(name = "document-info", required = true)
        protected FictionBook.Description.DocumentInfo documentInfo;
        @XmlElement(name = "publish-info")
        protected FictionBook.Description.PublishInfo publishInfo;
        @XmlElement(name = "custom-info")
        protected List<FictionBook.Description.CustomInfo> customInfo;

        /**
         * Gets the value of the titleInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FictionBook.Description.TitleInfo }
         *     
         */
        public FictionBook.Description.TitleInfo getTitleInfo() {
            return titleInfo;
        }

        /**
         * Sets the value of the titleInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FictionBook.Description.TitleInfo }
         *     
         */
        public void setTitleInfo(FictionBook.Description.TitleInfo value) {
            this.titleInfo = value;
        }

        /**
         * Gets the value of the documentInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FictionBook.Description.DocumentInfo }
         *     
         */
        public FictionBook.Description.DocumentInfo getDocumentInfo() {
            return documentInfo;
        }

        /**
         * Sets the value of the documentInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FictionBook.Description.DocumentInfo }
         *     
         */
        public void setDocumentInfo(FictionBook.Description.DocumentInfo value) {
            this.documentInfo = value;
        }

        /**
         * Gets the value of the publishInfo property.
         * 
         * @return
         *     possible object is
         *     {@link FictionBook.Description.PublishInfo }
         *     
         */
        public FictionBook.Description.PublishInfo getPublishInfo() {
            return publishInfo;
        }

        /**
         * Sets the value of the publishInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link FictionBook.Description.PublishInfo }
         *     
         */
        public void setPublishInfo(FictionBook.Description.PublishInfo value) {
            this.publishInfo = value;
        }

        /**
         * Gets the value of the customInfo property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customInfo property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomInfo().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FictionBook.Description.CustomInfo }
         * 
         * 
         */
        public List<FictionBook.Description.CustomInfo> getCustomInfo() {
            if (customInfo == null) {
                customInfo = new ArrayList<FictionBook.Description.CustomInfo>();
            }
            return this.customInfo;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0>textFieldType">
         *       &lt;attribute name="info-type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class CustomInfo
            extends TextFieldType
        {

            @XmlAttribute(name = "info-type", required = true)
            protected String infoType;

            /**
             * Gets the value of the infoType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInfoType() {
                return infoType;
            }

            /**
             * Sets the value of the infoType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInfoType(String value) {
                this.infoType = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="author" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded"/>
         *         &lt;element name="program-used" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType"/>
         *         &lt;element name="src-url" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="src-ocr" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}token"/>
         *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="history" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "author",
            "programUsed",
            "date",
            "srcUrl",
            "srcOcr",
            "id",
            "version",
            "history"
        })
        public static class DocumentInfo {

            @XmlElement(required = true)
            protected List<AuthorType> author;
            @XmlElement(name = "program-used")
            protected TextFieldType programUsed;
            @XmlElement(required = true)
            protected DateType date;
            @XmlElement(name = "src-url")
            protected List<String> srcUrl;
            @XmlElement(name = "src-ocr")
            protected TextFieldType srcOcr;
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected String id;
            protected float version;
            protected AnnotationType history;

            /**
             * Gets the value of the author property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the author property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AuthorType }
             * 
             * 
             */
            public List<AuthorType> getAuthor() {
                if (author == null) {
                    author = new ArrayList<AuthorType>();
                }
                return this.author;
            }

            /**
             * Gets the value of the programUsed property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getProgramUsed() {
                return programUsed;
            }

            /**
             * Sets the value of the programUsed property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setProgramUsed(TextFieldType value) {
                this.programUsed = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link DateType }
             *     
             */
            public DateType getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateType }
             *     
             */
            public void setDate(DateType value) {
                this.date = value;
            }

            /**
             * Gets the value of the srcUrl property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the srcUrl property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSrcUrl().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getSrcUrl() {
                if (srcUrl == null) {
                    srcUrl = new ArrayList<String>();
                }
                return this.srcUrl;
            }

            /**
             * Gets the value of the srcOcr property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getSrcOcr() {
                return srcOcr;
            }

            /**
             * Sets the value of the srcOcr property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setSrcOcr(TextFieldType value) {
                this.srcOcr = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the version property.
             * 
             */
            public float getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             */
            public void setVersion(float value) {
                this.version = value;
            }

            /**
             * Gets the value of the history property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotationType }
             *     
             */
            public AnnotationType getHistory() {
                return history;
            }

            /**
             * Sets the value of the history property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotationType }
             *     
             */
            public void setHistory(AnnotationType value) {
                this.history = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="book-name" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="publisher" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="city" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
         *         &lt;element name="isbn" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bookName",
            "publisher",
            "city",
            "year",
            "isbn",
            "sequence"
        })
        public static class PublishInfo {

            @XmlElement(name = "book-name")
            protected TextFieldType bookName;
            protected TextFieldType publisher;
            protected TextFieldType city;
            @XmlSchemaType(name = "gYear")
            protected XMLGregorianCalendar year;
            protected TextFieldType isbn;
            protected List<SequenceType> sequence;

            /**
             * Gets the value of the bookName property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getBookName() {
                return bookName;
            }

            /**
             * Sets the value of the bookName property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setBookName(TextFieldType value) {
                this.bookName = value;
            }

            /**
             * Gets the value of the publisher property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getPublisher() {
                return publisher;
            }

            /**
             * Sets the value of the publisher property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setPublisher(TextFieldType value) {
                this.publisher = value;
            }

            /**
             * Gets the value of the city property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getCity() {
                return city;
            }

            /**
             * Sets the value of the city property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setCity(TextFieldType value) {
                this.city = value;
            }

            /**
             * Gets the value of the year property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getYear() {
                return year;
            }

            /**
             * Sets the value of the year property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setYear(XMLGregorianCalendar value) {
                this.year = value;
            }

            /**
             * Gets the value of the isbn property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getIsbn() {
                return isbn;
            }

            /**
             * Sets the value of the isbn property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setIsbn(TextFieldType value) {
                this.isbn = value;
            }

            /**
             * Gets the value of the sequence property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sequence property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSequence().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SequenceType }
             * 
             * 
             */
            public List<SequenceType> getSequence() {
                if (sequence == null) {
                    sequence = new ArrayList<SequenceType>();
                }
                return this.sequence;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="genre" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0/genres>genreType">
         *                 &lt;attribute name="match" type="{http://www.w3.org/2001/XMLSchema}integer" default="100" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="author" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType">
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="book-title" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType"/>
         *         &lt;element name="annotation" type="{http://www.gribuser.ru/xml/fictionbook/2.0}annotationType" minOccurs="0"/>
         *         &lt;element name="keywords" type="{http://www.gribuser.ru/xml/fictionbook/2.0}textFieldType" minOccurs="0"/>
         *         &lt;element name="date" type="{http://www.gribuser.ru/xml/fictionbook/2.0}dateType" minOccurs="0"/>
         *         &lt;element name="coverpage" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" maxOccurs="unbounded"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="lang" type="{http://www.w3.org/2001/XMLSchema}language"/>
         *         &lt;element name="src-lang" type="{http://www.w3.org/2001/XMLSchema}language" minOccurs="0"/>
         *         &lt;element name="translator" type="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="sequence" type="{http://www.gribuser.ru/xml/fictionbook/2.0}sequenceType" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "genre",
            "author",
            "bookTitle",
            "annotation",
            "keywords",
            "date",
            "coverpage",
            "lang",
            "srcLang",
            "translator",
            "sequence"
        })
        public static class TitleInfo {

            @XmlElement(required = true)
            protected List<FictionBook.Description.TitleInfo.Genre> genre;
            @XmlElement(required = true)
            protected List<FictionBook.Description.TitleInfo.Author> author;
            @XmlElement(name = "book-title", required = true)
            protected TextFieldType bookTitle;
            protected AnnotationType annotation;
            protected TextFieldType keywords;
            protected DateType date;
            protected FictionBook.Description.TitleInfo.Coverpage coverpage;
            @XmlElement(required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "language")
            protected String lang;
            @XmlElement(name = "src-lang")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "language")
            protected String srcLang;
            protected List<AuthorType> translator;
            protected List<SequenceType> sequence;

            /**
             * Gets the value of the genre property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the genre property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGenre().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FictionBook.Description.TitleInfo.Genre }
             * 
             * 
             */
            public List<FictionBook.Description.TitleInfo.Genre> getGenre() {
                if (genre == null) {
                    genre = new ArrayList<FictionBook.Description.TitleInfo.Genre>();
                }
                return this.genre;
            }

            /**
             * Gets the value of the author property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the author property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAuthor().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link FictionBook.Description.TitleInfo.Author }
             * 
             * 
             */
            public List<FictionBook.Description.TitleInfo.Author> getAuthor() {
                if (author == null) {
                    author = new ArrayList<FictionBook.Description.TitleInfo.Author>();
                }
                return this.author;
            }

            /**
             * Gets the value of the bookTitle property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getBookTitle() {
                return bookTitle;
            }

            /**
             * Sets the value of the bookTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setBookTitle(TextFieldType value) {
                this.bookTitle = value;
            }

            /**
             * Gets the value of the annotation property.
             * 
             * @return
             *     possible object is
             *     {@link AnnotationType }
             *     
             */
            public AnnotationType getAnnotation() {
                return annotation;
            }

            /**
             * Sets the value of the annotation property.
             * 
             * @param value
             *     allowed object is
             *     {@link AnnotationType }
             *     
             */
            public void setAnnotation(AnnotationType value) {
                this.annotation = value;
            }

            /**
             * Gets the value of the keywords property.
             * 
             * @return
             *     possible object is
             *     {@link TextFieldType }
             *     
             */
            public TextFieldType getKeywords() {
                return keywords;
            }

            /**
             * Sets the value of the keywords property.
             * 
             * @param value
             *     allowed object is
             *     {@link TextFieldType }
             *     
             */
            public void setKeywords(TextFieldType value) {
                this.keywords = value;
            }

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link DateType }
             *     
             */
            public DateType getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link DateType }
             *     
             */
            public void setDate(DateType value) {
                this.date = value;
            }

            /**
             * Gets the value of the coverpage property.
             * 
             * @return
             *     possible object is
             *     {@link FictionBook.Description.TitleInfo.Coverpage }
             *     
             */
            public FictionBook.Description.TitleInfo.Coverpage getCoverpage() {
                return coverpage;
            }

            /**
             * Sets the value of the coverpage property.
             * 
             * @param value
             *     allowed object is
             *     {@link FictionBook.Description.TitleInfo.Coverpage }
             *     
             */
            public void setCoverpage(FictionBook.Description.TitleInfo.Coverpage value) {
                this.coverpage = value;
            }

            /**
             * Gets the value of the lang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLang() {
                return lang;
            }

            /**
             * Sets the value of the lang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLang(String value) {
                this.lang = value;
            }

            /**
             * Gets the value of the srcLang property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSrcLang() {
                return srcLang;
            }

            /**
             * Sets the value of the srcLang property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSrcLang(String value) {
                this.srcLang = value;
            }

            /**
             * Gets the value of the translator property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the translator property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTranslator().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AuthorType }
             * 
             * 
             */
            public List<AuthorType> getTranslator() {
                if (translator == null) {
                    translator = new ArrayList<AuthorType>();
                }
                return this.translator;
            }

            /**
             * Gets the value of the sequence property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the sequence property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSequence().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SequenceType }
             * 
             * 
             */
            public List<SequenceType> getSequence() {
                if (sequence == null) {
                    sequence = new ArrayList<SequenceType>();
                }
                return this.sequence;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://www.gribuser.ru/xml/fictionbook/2.0}authorType">
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Author
                extends AuthorType
            {


            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="image" type="{http://www.gribuser.ru/xml/fictionbook/2.0}imageType" maxOccurs="unbounded"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "image"
            })
            public static class Coverpage {

                @XmlElement(required = true)
                protected List<ImageType> image;

                /**
                 * Gets the value of the image property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the image property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getImage().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ImageType }
                 * 
                 * 
                 */
                public List<ImageType> getImage() {
                    if (image == null) {
                        image = new ArrayList<ImageType>();
                    }
                    return this.image;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.gribuser.ru/xml/fictionbook/2.0/genres>genreType">
             *       &lt;attribute name="match" type="{http://www.w3.org/2001/XMLSchema}integer" default="100" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Genre {

                @XmlValue
                protected GenreType value;
                @XmlAttribute(name = "match")
                protected BigInteger match;

                /**
                 * Gets the value of the value property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link GenreType }
                 *     
                 */
                public GenreType getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link GenreType }
                 *     
                 */
                public void setValue(GenreType value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the match property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getMatch() {
                    if (match == null) {
                        return new BigInteger("100");
                    } else {
                        return match;
                    }
                }

                /**
                 * Sets the value of the match property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setMatch(BigInteger value) {
                    this.match = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Stylesheet {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "type", required = true)
        protected String type;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getType() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setType(String value) {
            this.type = value;
        }

    }

}
