//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.02 at 11:54:56 AM EEST 
//


package org.fortune.schema._2_0;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Basic html-like tables
 * 
 * <p>Java class for tableType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tableType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tr" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="td" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="align" type="{http://www.gribuser.ru/xml/fictionbook/2.0}alignType" default="left" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tableType", propOrder = {
    "tr"
})
public class TableType {

    @XmlElement(required = true)
    protected List<TableType.Tr> tr;

    /**
     * Gets the value of the tr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TableType.Tr }
     * 
     * 
     */
    public List<TableType.Tr> getTr() {
        if (tr == null) {
            tr = new ArrayList<TableType.Tr>();
        }
        return this.tr;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="td" type="{http://www.gribuser.ru/xml/fictionbook/2.0}pType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="align" type="{http://www.gribuser.ru/xml/fictionbook/2.0}alignType" default="left" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "td"
    })
    public static class Tr {

        @XmlElement(required = true)
        protected List<PType> td;
        @XmlAttribute(name = "align")
        protected AlignType align;

        /**
         * Gets the value of the td property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the td property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTd().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PType }
         * 
         * 
         */
        public List<PType> getTd() {
            if (td == null) {
                td = new ArrayList<PType>();
            }
            return this.td;
        }

        /**
         * Gets the value of the align property.
         * 
         * @return
         *     possible object is
         *     {@link AlignType }
         *     
         */
        public AlignType getAlign() {
            if (align == null) {
                return AlignType.LEFT;
            } else {
                return align;
            }
        }

        /**
         * Sets the value of the align property.
         * 
         * @param value
         *     allowed object is
         *     {@link AlignType }
         *     
         */
        public void setAlign(AlignType value) {
            this.align = value;
        }

    }

}
